# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
fr:
  languageCode: fr
  contentDir: content/fr

#  Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en
  contentDir: content/en
  title: COLaF
  params:
    description: The COLaF project
  menu:
    main:
      - name: About
        url: '#about'
        weight: 1
      - name: Funding
        url: '#funding'
        weight: 20
      - name: Partners
        url: '#partners'
        weight: 30
      - name: Team
        url: '#team'
        weight: 40
      - name: Results
        url: 'results'
        weight: 50
      - name: Publications
        url: 'publications'
        weight: 60
      - name: Bibliographic sources
        url: 'https://colaf.huma-num.fr/bibliography'
        weight: 70
      - name: Identified ressources
        url: 'https://colaf.huma-num.fr/fr/Ressources.html'
        weight: 75
      - name: Contact
        url: '#contact'
        weight: 80

    
